#!/usr/bin/env ruby
# frozen_string_literal: true

require "goldlapel"

begin
  binary = GoldLapel::Proxy.find_binary
rescue RuntimeError => e
  $stderr.puts "Error: #{e.message}"
  exit 1
end

exec(binary, *ARGV)
